name: deployment
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: false
jobs:
    build:
        name: install and build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
            - name: Install dependences and build the app
              run: |
                  npm install
                  npm run build
            - name: Upload files
              uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: ./build    
    dev:
        needs: [build]
        name: deploy to dev
        runs-on: ubuntu-latest
        environment:
            name: development
        steps:
            - name: Deploy Github Pages
              uses: actions/deploy-pages@v4
    prod:
        needs: [build]
        name: deploy to production
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Deploy production
              run: |
                  npm install
                  npm run build
