name: deployment
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    dev:
        name: deploy to dev
        runs-on: ubuntu-latest
        environment:
            name: development
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Deploy
              run: npm install
